// <auto-generated />
namespace AdminDaLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Batch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Batch));
        
        string IMigrationMetadata.Id
        {
            get { return "202105041441293_add_Batch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
