// <auto-generated />
namespace AdminDaLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class module_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(module_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202105040359120_module_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
